/**
 * Auto-generated TypeScript types for Svelte components
 * 
 * Generated by: generate-svelte-types.php
 * Do not edit manually - run the generator to update
 * 
 * Usage:
 * import type { ArticleListProps } from './svelte-components';
 */

declare module '*.svelte' {
    import { SvelteComponent } from 'svelte';
    export default SvelteComponent;
}

// Component constructors
declare global {
}

export {};
