/**
 * Auto-generated TypeScript types for Svelte components
 * 
 * Generated by: generate-svelte-types.php
 * Do not edit manually - run the generator to update
 * 
 * Usage:
 * import type { ArticleListProps } from './svelte-components';
 */

declare module '*.svelte' {
    import { SvelteComponent } from 'svelte';
    export default SvelteComponent;
}

/**
 * Props for ArticleList component
 */
export interface ArticleListProps {
  articles?: any[];
  searchQuery?: string;
}

/**
 * Props for Card component
 */
export interface CardProps {
  title?: string;
  excerpt?: string;
  href?: string;
  image?: any;
  tags?: any[];
  date?: any;
  animate?: boolean;
}

/**
 * Props for ContactForm component
 */
export interface ContactFormProps {
  actionUrl?: string;
  csrfToken?: string;
}

/**
 * Props for Navigation component
 */
export interface NavigationProps {
  // No props defined
}

/**
 * Props for ThemeToggle component
 */
export interface ThemeToggleProps {
  // No props defined
}

/**
 * Props for ThemeToggleSimple component
 */
export interface ThemeToggleSimpleProps {
  // No props defined
}

/**
 * Props for Toast component
 */
export interface ToastProps {
  // No props defined
}

// Component constructors
declare global {
  interface Window {
    ArticleList: typeof import('../svelte/components/ArticleList.svelte').default;
  }
  interface Window {
    Card: typeof import('../svelte/components/Card.svelte').default;
  }
  interface Window {
    ContactForm: typeof import('../svelte/components/ContactForm.svelte').default;
  }
  interface Window {
    Navigation: typeof import('../svelte/components/Navigation.svelte').default;
  }
  interface Window {
    ThemeToggle: typeof import('../svelte/components/ThemeToggle.svelte').default;
  }
  interface Window {
    ThemeToggleSimple: typeof import('../svelte/components/ThemeToggleSimple.svelte').default;
  }
  interface Window {
    Toast: typeof import('../svelte/components/Toast.svelte').default;
  }
}

export {};
