#!/usr/bin/env php
<?php

/**
 * Svelte Component Type Generator
 * 
 * Automatically generates TypeScript types for Svelte components
 * by parsing .svelte files and extracting props.
 * 
 * Usage: php generate-svelte-types.php
 */

declare(strict_types=1);

$rootDir = '/home/evan/dev/nativa-php-boot';
$svelteDir = $rootDir . '/src/Templates/svelte/components';
$outputDir = $rootDir . '/src/Templates/src/types';
$outputFile = $outputDir . '/svelte-components.d.ts';

// Ensure output directory exists
if (!is_dir($outputDir)) {
    mkdir($outputDir, 0755, true);
}

echo "🔍 Scanning Svelte components in: $svelteDir\n\n";

$components = [];
$files = glob($svelteDir . '/*.svelte');

foreach ($files as $file) {
    $componentName = basename($file, '.svelte');
    echo "📄 Processing: $componentName.svelte\n";
    
    $content = file_get_contents($file);
    $props = extractProps($content);
    
    $components[$componentName] = [
        'name' => $componentName,
        'props' => $props,
        'file' => $file,
    ];
}

echo "\n✨ Generating TypeScript definitions...\n";

$types = generateTypeDefinitions($components);

file_put_contents($outputFile, $types);

echo "✅ Generated: $outputFile\n";
echo "📦 Total components: " . count($components) . "\n\n";

// List all generated types
foreach ($components as $component) {
    $propCount = count($component['props']);
    echo "  - {$component['name']}Props ($propCount props)\n";
}

echo "\n🎉 Done!\n";

/**
 * Extract props from Svelte component
 */
function extractProps(string $content): array
{
    $props = [];
    
    // Match Svelte 5 $props() syntax
    // let { prop1, prop2 = 'default' } = $props();
    if (preg_match('/let\s*\{\s*([^}]+)\s*\}\s*=\s*\$props\(\)/s', $content, $matches)) {
        $propsString = $matches[1];
        
        // Split by comma and parse each prop
        $propStrings = preg_split('/,\s*/', trim($propsString));
        
        foreach ($propStrings as $propString) {
            $propString = trim($propString);
            
            // Match prop with default value: propName = 'default'
            if (preg_match('/^(\w+)\s*=\s*(.+)$/', $propString, $propMatches)) {
                $props[] = [
                    'name' => $propMatches[1],
                    'default' => $propMatches[2],
                    'type' => inferType($propMatches[2]),
                    'required' => false,
                ];
            } else {
                // Prop without default value
                $props[] = [
                    'name' => $propString,
                    'default' => null,
                    'type' => 'any',
                    'required' => true,
                ];
            }
        }
    }
    
    // Also match old export let syntax (for compatibility)
    if (preg_match_all('/export\s+let\s+(\w+)(?:\s*=\s*(.+))?;/m', $content, $matches, PREG_SET_ORDER)) {
        foreach ($matches as $match) {
            // Skip if already found via $props()
            $exists = false;
            foreach ($props as $prop) {
                if ($prop['name'] === $match[1]) {
                    $exists = true;
                    break;
                }
            }
            
            if (!$exists) {
                $props[] = [
                    'name' => $match[1],
                    'default' => $match[2] ?? null,
                    'type' => $match[2] ? inferType($match[2]) : 'any',
                    'required' => empty($match[2]),
                ];
            }
        }
    }
    
    return $props;
}

/**
 * Infer TypeScript type from default value
 */
function inferType(string $value): string
{
    $value = trim($value);
    
    if ($value === 'true' || $value === 'false') {
        return 'boolean';
    }
    
    if (is_numeric($value)) {
        return 'number';
    }
    
    if (str_starts_with($value, "'") || str_starts_with($value, '"')) {
        return 'string';
    }
    
    if (str_starts_with($value, '[')) {
        return 'any[]';
    }
    
    if (str_starts_with($value, '{')) {
        return 'Record<string, any>';
    }
    
    if ($value === 'null' || $value === 'undefined') {
        return 'any';
    }
    
    return 'any';
}

/**
 * Generate TypeScript definition file
 */
function generateTypeDefinitions(array $components): string
{
    $output = <<<HEADER
/**
 * Auto-generated TypeScript types for Svelte components
 * 
 * Generated by: generate-svelte-types.php
 * Do not edit manually - run the generator to update
 * 
 * Usage:
 * import type { ArticleListProps } from './svelte-components';
 */

declare module '*.svelte' {
    import { SvelteComponent } from 'svelte';
    export default SvelteComponent;
}

HEADER;

    foreach ($components as $component) {
        $output .= "\n";
        $output .= "/**\n";
        $output .= " * Props for {$component['name']} component\n";
        $output .= " */\n";
        $output .= "export interface {$component['name']}Props {\n";
        
        if (empty($component['props'])) {
            $output .= "  // No props defined\n";
        } else {
            foreach ($component['props'] as $prop) {
                $required = $prop['required'] ? '' : '?';
                $output .= "  {$prop['name']}{$required}: {$prop['type']};\n";
            }
        }
        
        $output .= "}\n";
    }

    $output .= "\n";
    $output .= "// Component constructors\n";
    $output .= "declare global {\n";
    
    foreach ($components as $component) {
        $output .= "  interface Window {\n";
        $output .= "    {$component['name']}: typeof import('../svelte/components/{$component['name']}.svelte').default;\n";
        $output .= "  }\n";
    }
    
    $output .= "}\n";
    
    $output .= "\nexport {};\n";

    return $output;
}
