<?php

declare(strict_types = 1);
// [STAMP] ef71d23865540c19c424f13b54a446d6
// phpcs:ignoreFile

namespace Tests\Support\_generated;

use Codeception\Module\AbstractAsserts;
use Codeception\Module\Asserts;
use Codeception\Scenario;
use Codeception\Step\Action;
use PHPUnit\Framework\Constraint\Constraint;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build

trait UnitTesterActions
{
    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Handles and checks throwables (Exceptions/Errors) called inside the callback function.
     * Either throwable class name or throwable instance should be provided.
     *
     * ```php
     * <?php
     * $I->expectThrowable(MyThrowable::class, function() {
     *     $this->doSomethingBad();
     * });
     *
     * $I->expectThrowable(new MyException(), function() {
     *     $this->doSomethingBad();
     * });
     * ```
     *
     * If you want to check message or throwable code, you can pass them with throwable instance:
     * ```php
     * <?php
     * // will check that throwable MyError is thrown with "Don't do bad things" message
     * $I->expectThrowable(new MyError("Don't do bad things"), function() {
     *     $this->doSomethingBad();
     * });
     * ```
     *
     * @see Asserts::expectThrowable()
     */
    public function expectThrowable(string | \Throwable $throwable, callable $callback): void
    {
        $this->getScenario()->runStep(new Action('expectThrowable', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a file does not exist.
     *
     * @see AbstractAsserts::assertFileNotExists()
     */
    public function assertFileNotExists(string $filename, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertFileNotExists', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a value is greater than or equal to another value.
     *
     * @param mixed $expected
     * @param mixed $actual
     *
     * @see AbstractAsserts::assertGreaterOrEquals()
     */
    public function assertGreaterOrEquals($expected, $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertGreaterOrEquals', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is empty.
     *
     * @see AbstractAsserts::assertIsEmpty()
     */
    public function assertIsEmpty(mixed $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsEmpty', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a value is smaller than or equal to another value.
     *
     * @see AbstractAsserts::assertLessOrEquals()
     */
    public function assertLessOrEquals(mixed $expected, mixed $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertLessOrEquals', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a string does not match a given regular expression.
     *
     * @see AbstractAsserts::assertNotRegExp()
     */
    public function assertNotRegExp(string $pattern, string $string, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertNotRegExp', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a string matches a given regular expression.
     *
     * @see AbstractAsserts::assertRegExp()
     */
    public function assertRegExp(string $pattern, string $string, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertRegExp', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Evaluates a PHPUnit\Framework\Constraint matcher object.
     *
     * @see AbstractAsserts::assertThatItsNot()
     */
    public function assertThatItsNot(mixed $value, Constraint $constraint, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertThatItsNot', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that an array has a specified key.
     *
     * @param array<mixed>|ArrayAccess<mixed, mixed> $array
     *
     * @see AbstractAsserts::assertArrayHasKey()
     */
    public function assertArrayHasKey(int | string $key, array | \ArrayAccess $array, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertArrayHasKey', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that an array does not have a specified key.
     *
     * @param array<mixed>|ArrayAccess<mixed, mixed> $array
     *
     * @see AbstractAsserts::assertArrayNotHasKey()
     */
    public function assertArrayNotHasKey(int | string $key, array | \ArrayAccess $array, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertArrayNotHasKey', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a class has a specified attribute.
     *
     * @param class-string $className
     *
     * @see AbstractAsserts::assertClassHasAttribute()
     */
    public function assertClassHasAttribute(string $attributeName, string $className, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertClassHasAttribute', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a class has a specified static attribute.
     *
     * @param class-string $className
     *
     * @see AbstractAsserts::assertClassHasStaticAttribute()
     */
    public function assertClassHasStaticAttribute(string $attributeName, string $className, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertClassHasStaticAttribute', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a class does not have a specified attribute.
     *
     * @param class-string $className
     *
     * @see AbstractAsserts::assertClassNotHasAttribute()
     */
    public function assertClassNotHasAttribute(string $attributeName, string $className, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertClassNotHasAttribute', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a class does not have a specified static attribute.
     *
     * @param class-string $className
     *
     * @see AbstractAsserts::assertClassNotHasStaticAttribute()
     */
    public function assertClassNotHasStaticAttribute(string $attributeName, string $className, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertClassNotHasStaticAttribute', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a haystack contains a needle.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContains()
     */
    public function assertContains(mixed $needle, iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContains', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsEquals()
     */
    public function assertContainsEquals(mixed $needle, iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsEquals', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertNotContainsEquals()
     */
    public function assertNotContainsEquals(mixed $needle, iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertNotContainsEquals', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsNotOnlyArray()
     */
    public function assertContainsNotOnlyArray(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsNotOnlyArray', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsNotOnlyBool()
     */
    public function assertContainsNotOnlyBool(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsNotOnlyBool', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsNotOnlyCallable()
     */
    public function assertContainsNotOnlyCallable(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsNotOnlyCallable', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsNotOnlyFloat()
     */
    public function assertContainsNotOnlyFloat(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsNotOnlyFloat', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param class-string    $className
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsNotOnlyInstancesOf()
     */
    public function assertContainsNotOnlyInstancesOf(string $className, iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsNotOnlyInstancesOf', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsNotOnlyInt()
     */
    public function assertContainsNotOnlyInt(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsNotOnlyInt', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsNotOnlyIterable()
     */
    public function assertContainsNotOnlyIterable(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsNotOnlyIterable', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsNotOnlyNull()
     */
    public function assertContainsNotOnlyNull(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsNotOnlyNull', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsNotOnlyNumeric()
     */
    public function assertContainsNotOnlyNumeric(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsNotOnlyNumeric', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsNotOnlyObject()
     */
    public function assertContainsNotOnlyObject(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsNotOnlyObject', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsNotOnlyResource()
     */
    public function assertContainsNotOnlyResource(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsNotOnlyResource', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsNotOnlyClosedResource()
     */
    public function assertContainsNotOnlyClosedResource(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsNotOnlyClosedResource', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsNotOnlyScalar()
     */
    public function assertContainsNotOnlyScalar(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsNotOnlyScalar', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsNotOnlyString()
     */
    public function assertContainsNotOnlyString(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsNotOnlyString', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a haystack contains only values of a given type.
     *
     * @param 'array'|'bool'|'boolean'|'callable'|'double'|'float'|'int'|'integer'|'iterable'|'null'|'numeric'|'object'|'real'|'resource'|'resource (closed)'|'scalar'|'string'|class-string $type
     * @param iterable<mixed>                                                                                                                                                                $haystack
     *
     * @see AbstractAsserts::assertContainsOnly()
     */
    public function assertContainsOnly(string $type, iterable $haystack, ?bool $isNativeType = null, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsOnly', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a haystack contains only instances of a given class name.
     *
     * @param class-string    $className
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsOnlyInstancesOf()
     */
    public function assertContainsOnlyInstancesOf(string $className, iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsOnlyInstancesOf', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsOnlyArray()
     */
    public function assertContainsOnlyArray(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsOnlyArray', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsOnlyBool()
     */
    public function assertContainsOnlyBool(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsOnlyBool', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsOnlyCallable()
     */
    public function assertContainsOnlyCallable(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsOnlyCallable', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsOnlyFloat()
     */
    public function assertContainsOnlyFloat(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsOnlyFloat', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsOnlyInt()
     */
    public function assertContainsOnlyInt(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsOnlyInt', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsOnlyIterable()
     */
    public function assertContainsOnlyIterable(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsOnlyIterable', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsOnlyNull()
     */
    public function assertContainsOnlyNull(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsOnlyNull', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsOnlyNumeric()
     */
    public function assertContainsOnlyNumeric(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsOnlyNumeric', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsOnlyObject()
     */
    public function assertContainsOnlyObject(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsOnlyObject', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsOnlyResource()
     */
    public function assertContainsOnlyResource(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsOnlyResource', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsOnlyClosedResource()
     */
    public function assertContainsOnlyClosedResource(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsOnlyClosedResource', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsOnlyScalar()
     */
    public function assertContainsOnlyScalar(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsOnlyScalar', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertContainsOnlyString()
     */
    public function assertContainsOnlyString(iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertContainsOnlyString', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts the number of elements of an array, Countable or Traversable.
     *
     * @param \Countable|iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertCount()
     */
    public function assertCount(int $expectedCount, array | \Countable | \Traversable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertCount', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a directory does not exist.
     *
     * @see AbstractAsserts::assertDirectoryDoesNotExist()
     */
    public function assertDirectoryDoesNotExist(string $directory, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertDirectoryDoesNotExist', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a directory exists.
     *
     * @see AbstractAsserts::assertDirectoryExists()
     */
    public function assertDirectoryExists(string $directory, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertDirectoryExists', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a directory exists and is not readable.
     *
     * @see AbstractAsserts::assertDirectoryIsNotReadable()
     */
    public function assertDirectoryIsNotReadable(string $directory, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertDirectoryIsNotReadable', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a directory exists and is not writable.
     *
     * @see AbstractAsserts::assertDirectoryIsNotWritable()
     */
    public function assertDirectoryIsNotWritable(string $directory, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertDirectoryIsNotWritable', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a directory exists and is readable.
     *
     * @see AbstractAsserts::assertDirectoryIsReadable()
     */
    public function assertDirectoryIsReadable(string $directory, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertDirectoryIsReadable', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a directory exists and is writable.
     *
     * @see AbstractAsserts::assertDirectoryIsWritable()
     */
    public function assertDirectoryIsWritable(string $directory, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertDirectoryIsWritable', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a string does not match a given regular expression.
     *
     * @see AbstractAsserts::assertDoesNotMatchRegularExpression()
     */
    public function assertDoesNotMatchRegularExpression(string $pattern, string $string, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertDoesNotMatchRegularExpression', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is empty.
     *
     * @param mixed $actual
     *
     * @phpstan-assert empty $actual
     *
     * @see AbstractAsserts::assertEmpty()
     */
    public function assertEmpty($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertEmpty', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that two variables are equal.
     *
     * @param mixed $expected
     * @param mixed $actual
     *
     * @see AbstractAsserts::assertEquals()
     */
    public function assertEquals($expected, $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertEquals', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that two variables are equal (canonicalizing).
     *
     * @param mixed $expected
     * @param mixed $actual
     *
     * @see AbstractAsserts::assertEqualsCanonicalizing()
     */
    public function assertEqualsCanonicalizing($expected, $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertEqualsCanonicalizing', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that two variables are equal (ignoring case).
     *
     * @param mixed $expected
     * @param mixed $actual
     *
     * @see AbstractAsserts::assertEqualsIgnoringCase()
     */
    public function assertEqualsIgnoringCase($expected, $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertEqualsIgnoringCase', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that two variables are equal (with delta).
     *
     * @param mixed $expected
     * @param mixed $actual
     *
     * @see AbstractAsserts::assertEqualsWithDelta()
     */
    public function assertEqualsWithDelta($expected, $actual, float $delta, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertEqualsWithDelta', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a condition is false.
     *
     * @param mixed $condition
     *
     * @phpstan-assert false $condition
     *
     * @see AbstractAsserts::assertFalse()
     */
    public function assertFalse($condition, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertFalse', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a file does not exist.
     *
     * @see AbstractAsserts::assertFileDoesNotExist()
     */
    public function assertFileDoesNotExist(string $filename, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertFileDoesNotExist', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that the contents of one file is equal to the contents of another file.
     *
     * @see AbstractAsserts::assertFileEquals()
     */
    public function assertFileEquals(string $expected, string $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertFileEquals', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that the contents of one file is equal to the contents of another file (canonicalizing).
     *
     * @see AbstractAsserts::assertFileEqualsCanonicalizing()
     */
    public function assertFileEqualsCanonicalizing(string $expected, string $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertFileEqualsCanonicalizing', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that the contents of one file is equal to the contents of another file (ignoring case).
     *
     * @see AbstractAsserts::assertFileEqualsIgnoringCase()
     */
    public function assertFileEqualsIgnoringCase(string $expected, string $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertFileEqualsIgnoringCase', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a file exists.
     *
     * @see AbstractAsserts::assertFileExists()
     */
    public function assertFileExists(string $filename, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertFileExists', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a file exists and is not readable.
     *
     * @see AbstractAsserts::assertFileIsNotReadable()
     */
    public function assertFileIsNotReadable(string $file, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertFileIsNotReadable', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a file exists and is not writable.
     *
     * @see AbstractAsserts::assertFileIsNotWritable()
     */
    public function assertFileIsNotWritable(string $file, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertFileIsNotWritable', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a file exists and is readable.
     *
     * @see AbstractAsserts::assertFileIsReadable()
     */
    public function assertFileIsReadable(string $file, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertFileIsReadable', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a file exists and is writable.
     *
     * @see AbstractAsserts::assertFileIsWritable()
     */
    public function assertFileIsWritable(string $file, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertFileIsWritable', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that the contents of one file is not equal to the contents of another file.
     *
     * @see AbstractAsserts::assertFileNotEquals()
     */
    public function assertFileNotEquals(string $expected, string $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertFileNotEquals', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that the contents of one file is not equal to the contents of another file (canonicalizing).
     *
     * @see AbstractAsserts::assertFileNotEqualsCanonicalizing()
     */
    public function assertFileNotEqualsCanonicalizing(string $expected, string $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertFileNotEqualsCanonicalizing', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that the contents of one file is not equal to the contents of another file (ignoring case).
     *
     * @see AbstractAsserts::assertFileNotEqualsIgnoringCase()
     */
    public function assertFileNotEqualsIgnoringCase(string $expected, string $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertFileNotEqualsIgnoringCase', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is finite.
     *
     * @param mixed $actual
     *
     * @see AbstractAsserts::assertFinite()
     */
    public function assertFinite($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertFinite', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a value is greater than another value.
     *
     * @param mixed $expected
     * @param mixed $actual
     *
     * @see AbstractAsserts::assertGreaterThan()
     */
    public function assertGreaterThan($expected, $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertGreaterThan', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a value is greater than or equal to another value.
     *
     * @param mixed $expected
     * @param mixed $actual
     *
     * @see AbstractAsserts::assertGreaterThanOrEqual()
     */
    public function assertGreaterThanOrEqual($expected, $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertGreaterThanOrEqual', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is infinite.
     *
     * @param mixed $actual
     *
     * @see AbstractAsserts::assertInfinite()
     */
    public function assertInfinite($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertInfinite', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is of a given type.
     *
     * @template ExpectedType of object
     *
     * @param mixed                      $actual
     * @param class-string<ExpectedType> $expected
     *
     * @phpstan-assert =ExpectedType $actual
     *
     * @see AbstractAsserts::assertInstanceOf()
     */
    public function assertInstanceOf(string $expected, $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertInstanceOf', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is of type array.
     *
     * @param mixed $actual
     *
     * @phpstan-assert array<mixed> $actual
     *
     * @see AbstractAsserts::assertIsArray()
     */
    public function assertIsArray($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsArray', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is of type bool.
     *
     * @param mixed $actual
     *
     * @phpstan-assert bool $actual
     *
     * @see AbstractAsserts::assertIsBool()
     */
    public function assertIsBool($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsBool', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is of type callable.
     *
     * @param mixed $actual
     *
     * @phpstan-assert callable $actual
     *
     * @see AbstractAsserts::assertIsCallable()
     */
    public function assertIsCallable($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsCallable', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is of type resource and is closed.
     *
     * @param mixed $actual
     *
     * @phpstan-assert resource $actual
     *
     * @see AbstractAsserts::assertIsClosedResource()
     */
    public function assertIsClosedResource($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsClosedResource', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is of type float.
     *
     * @param mixed $actual
     *
     * @phpstan-assert float $actual
     *
     * @see AbstractAsserts::assertIsFloat()
     */
    public function assertIsFloat($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsFloat', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is of type int.
     *
     * @param mixed $actual
     *
     * @phpstan-assert int $actual
     *
     * @see AbstractAsserts::assertIsInt()
     */
    public function assertIsInt($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsInt', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is of type iterable.
     *
     * @param mixed $actual
     *
     * @phpstan-assert iterable<mixed> $actual
     *
     * @see AbstractAsserts::assertIsIterable()
     */
    public function assertIsIterable($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsIterable', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is not of type array.
     *
     * @param mixed $actual
     *
     * @phpstan-assert !array<mixed> $actual
     *
     * @see AbstractAsserts::assertIsNotArray()
     */
    public function assertIsNotArray($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsNotArray', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is not of type bool.
     *
     * @param mixed $actual
     *
     * @phpstan-assert !bool $actual
     *
     * @see AbstractAsserts::assertIsNotBool()
     */
    public function assertIsNotBool($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsNotBool', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is not of type callable.
     *
     * @param mixed $actual
     *
     * @phpstan-assert !callable $actual
     *
     * @see AbstractAsserts::assertIsNotCallable()
     */
    public function assertIsNotCallable($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsNotCallable', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is not of type resource.
     *
     * @param mixed $actual
     *
     * @phpstan-assert !resource $actual
     *
     * @see AbstractAsserts::assertIsNotClosedResource()
     */
    public function assertIsNotClosedResource($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsNotClosedResource', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is not of type float.
     *
     * @param mixed $actual
     *
     * @phpstan-assert !float $actual
     *
     * @see AbstractAsserts::assertIsNotFloat()
     */
    public function assertIsNotFloat($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsNotFloat', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is not of type int.
     *
     * @param mixed $actual
     *
     * @phpstan-assert !int $actual
     *
     * @see AbstractAsserts::assertIsNotInt()
     */
    public function assertIsNotInt($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsNotInt', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is not of type iterable.
     *
     * @param mixed $actual
     *
     * @phpstan-assert !iterable<mixed> $actual
     *
     * @see AbstractAsserts::assertIsNotIterable()
     */
    public function assertIsNotIterable($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsNotIterable', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is not of type numeric.
     *
     * @param mixed $actual
     *
     * @phpstan-assert !numeric $actual
     *
     * @see AbstractAsserts::assertIsNotNumeric()
     */
    public function assertIsNotNumeric($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsNotNumeric', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is not of type object.
     *
     * @param mixed $actual
     *
     * @phpstan-assert !object $actual
     *
     * @see AbstractAsserts::assertIsNotObject()
     */
    public function assertIsNotObject($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsNotObject', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a file/dir exists and is not readable.
     *
     * @see AbstractAsserts::assertIsNotReadable()
     */
    public function assertIsNotReadable(string $filename, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsNotReadable', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is not of type resource.
     *
     * @param mixed $actual
     *
     * @phpstan-assert !resource $actual
     *
     * @see AbstractAsserts::assertIsNotResource()
     */
    public function assertIsNotResource($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsNotResource', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is not of type scalar.
     *
     * @param mixed $actual
     *
     * @psalm-assert !scalar $actual
     *
     * @see AbstractAsserts::assertIsNotScalar()
     */
    public function assertIsNotScalar($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsNotScalar', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is not of type string.
     *
     * @param mixed $actual
     *
     * @phpstan-assert !string $actual
     *
     * @see AbstractAsserts::assertIsNotString()
     */
    public function assertIsNotString($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsNotString', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a file/dir exists and is not writable.
     *
     * @see AbstractAsserts::assertIsNotWritable()
     */
    public function assertIsNotWritable(string $filename, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsNotWritable', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is of type numeric.
     *
     * @param mixed $actual
     *
     * @phpstan-assert numeric $actual
     *
     * @see AbstractAsserts::assertIsNumeric()
     */
    public function assertIsNumeric($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsNumeric', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is of type object.
     *
     * @param mixed $actual
     *
     * @phpstan-assert object $actual
     *
     * @see AbstractAsserts::assertIsObject()
     */
    public function assertIsObject($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsObject', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a file/dir is readable.
     *
     * @see AbstractAsserts::assertIsReadable()
     */
    public function assertIsReadable(string $filename, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsReadable', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is of type resource.
     *
     * @param mixed $actual
     *
     * @phpstan-assert resource $actual
     *
     * @see AbstractAsserts::assertIsResource()
     */
    public function assertIsResource($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsResource', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is of type scalar.
     *
     * @param mixed $actual
     *
     * @phpstan-assert scalar $actual
     *
     * @see AbstractAsserts::assertIsScalar()
     */
    public function assertIsScalar($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsScalar', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is of type string.
     *
     * @param mixed $actual
     *
     * @phpstan-assert string $actual
     *
     * @see AbstractAsserts::assertIsString()
     */
    public function assertIsString($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsString', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a file/dir exists and is writable.
     *
     * @see AbstractAsserts::assertIsWritable()
     */
    public function assertIsWritable(string $filename, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertIsWritable', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a string is a valid JSON string.
     *
     * @see AbstractAsserts::assertJson()
     */
    public function assertJson(string $actualJson, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertJson', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that two JSON files are equal.
     *
     * @see AbstractAsserts::assertJsonFileEqualsJsonFile()
     */
    public function assertJsonFileEqualsJsonFile(string $expectedFile, string $actualFile, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertJsonFileEqualsJsonFile', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that two JSON files are not equal.
     *
     * @see AbstractAsserts::assertJsonFileNotEqualsJsonFile()
     */
    public function assertJsonFileNotEqualsJsonFile(string $expectedFile, string $actualFile, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertJsonFileNotEqualsJsonFile', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that the generated JSON encoded object and the content of the given file are equal.
     *
     * @see AbstractAsserts::assertJsonStringEqualsJsonFile()
     */
    public function assertJsonStringEqualsJsonFile(string $expectedFile, string $actualJson, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertJsonStringEqualsJsonFile', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that two given JSON encoded objects or arrays are equal.
     *
     * @see AbstractAsserts::assertJsonStringEqualsJsonString()
     */
    public function assertJsonStringEqualsJsonString(string $expectedJson, string $actualJson, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertJsonStringEqualsJsonString', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that the generated JSON encoded object and the content of the given file are not equal.
     *
     * @see AbstractAsserts::assertJsonStringNotEqualsJsonFile()
     */
    public function assertJsonStringNotEqualsJsonFile(string $expectedFile, string $actualJson, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertJsonStringNotEqualsJsonFile', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that two given JSON encoded objects or arrays are not equal.
     *
     * @see AbstractAsserts::assertJsonStringNotEqualsJsonString()
     */
    public function assertJsonStringNotEqualsJsonString(string $expectedJson, string $actualJson, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertJsonStringNotEqualsJsonString', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a value is smaller than another value.
     *
     * @param mixed $expected
     * @param mixed $actual
     *
     * @see AbstractAsserts::assertLessThan()
     */
    public function assertLessThan($expected, $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertLessThan', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a value is smaller than or equal to another value.
     *
     * @param mixed $expected
     * @param mixed $actual
     *
     * @see AbstractAsserts::assertLessThanOrEqual()
     */
    public function assertLessThanOrEqual($expected, $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertLessThanOrEqual', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a string matches a given regular expression.
     *
     * @see AbstractAsserts::assertMatchesRegularExpression()
     */
    public function assertMatchesRegularExpression(string $pattern, string $string, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertMatchesRegularExpression', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is nan.
     *
     * @param mixed $actual
     *
     * @see AbstractAsserts::assertNan()
     */
    public function assertNan($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertNan', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a haystack does not contain a needle.
     *
     * @param iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertNotContains()
     */
    public function assertNotContains(mixed $needle, iterable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertNotContains', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a haystack does not contain only values of a given type.
     *
     * @param 'array'|'bool'|'boolean'|'callable'|'double'|'float'|'int'|'integer'|'iterable'|'null'|'numeric'|'object'|'real'|'resource'|'resource (closed)'|'scalar'|'string'|class-string $type
     * @param iterable<mixed>                                                                                                                                                                $haystack
     *
     * @see AbstractAsserts::assertNotContainsOnly()
     */
    public function assertNotContainsOnly(string $type, iterable $haystack, ?bool $isNativeType = null, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertNotContainsOnly', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts the number of elements of an array, Countable or Traversable.
     *
     * @param \Countable|iterable<mixed> $haystack
     *
     * @see AbstractAsserts::assertNotCount()
     */
    public function assertNotCount(int $expectedCount, array | \Countable | \Traversable $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertNotCount', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is not empty.
     *
     * @param mixed $actual
     *
     * @phpstan-assert !empty $actual
     *
     * @see AbstractAsserts::assertNotEmpty()
     */
    public function assertNotEmpty($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertNotEmpty', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that two variables are not equal.
     *
     * @param mixed $expected
     * @param mixed $actual
     *
     * @see AbstractAsserts::assertNotEquals()
     */
    public function assertNotEquals($expected, $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertNotEquals', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that two variables are not equal (canonicalizing).
     *
     * @param mixed $expected
     * @param mixed $actual
     *
     * @see AbstractAsserts::assertNotEqualsCanonicalizing()
     */
    public function assertNotEqualsCanonicalizing($expected, $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertNotEqualsCanonicalizing', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that two variables are not equal (ignoring case).
     *
     * @param mixed $expected
     * @param mixed $actual
     *
     * @see AbstractAsserts::assertNotEqualsIgnoringCase()
     */
    public function assertNotEqualsIgnoringCase($expected, $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertNotEqualsIgnoringCase', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that two variables are not equal (with delta).
     *
     * @param mixed $expected
     * @param mixed $actual
     *
     * @see AbstractAsserts::assertNotEqualsWithDelta()
     */
    public function assertNotEqualsWithDelta($expected, $actual, float $delta, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertNotEqualsWithDelta', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a condition is not false.
     *
     * @param mixed $condition
     *
     * @phpstan-assert !false $condition
     *
     * @see AbstractAsserts::assertNotFalse()
     */
    public function assertNotFalse($condition, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertNotFalse', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is not of a given type.
     *
     * @template ExpectedType of object
     *
     * @param mixed                      $actual
     * @param class-string<ExpectedType> $expected
     *
     * @phpstan-assert !ExpectedType $actual
     *
     * @see AbstractAsserts::assertNotInstanceOf()
     */
    public function assertNotInstanceOf(string $expected, $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertNotInstanceOf', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is not null.
     *
     * @param mixed $actual
     *
     * @phpstan-assert !null $actual
     *
     * @see AbstractAsserts::assertNotNull()
     */
    public function assertNotNull($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertNotNull', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that two variables do not have the same type and value.
     *
     * @param mixed $expected
     * @param mixed $actual
     *
     * @see AbstractAsserts::assertNotSame()
     */
    public function assertNotSame($expected, $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertNotSame', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Assert that the size of two arrays (or `Countable` or `Traversable` objects) is not the same.
     *
     * @param \Countable|iterable<mixed> $expected
     * @param \Countable|iterable<mixed> $actual
     *
     * @see AbstractAsserts::assertNotSameSize()
     */
    public function assertNotSameSize(array | \Countable | \Traversable $expected, array | \Countable | \Traversable $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertNotSameSize', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a condition is not true.
     *
     * @param mixed $condition
     *
     * @phpstan-assert !true $condition
     *
     * @see AbstractAsserts::assertNotTrue()
     */
    public function assertNotTrue($condition, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertNotTrue', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a variable is null.
     *
     * @param mixed $actual
     *
     * @phpstan-assert null $actual
     *
     * @see AbstractAsserts::assertNull()
     */
    public function assertNull($actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertNull', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that an object has a specified attribute.
     *
     * @see AbstractAsserts::assertObjectHasAttribute()
     */
    public function assertObjectHasAttribute(string $attributeName, object $object, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertObjectHasAttribute', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that an object does not have a specified attribute.
     *
     * @see AbstractAsserts::assertObjectNotHasAttribute()
     */
    public function assertObjectNotHasAttribute(string $attributeName, object $object, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertObjectNotHasAttribute', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that two variables have the same type and value.
     * Used on objects, it asserts that two variables reference
     * the same object.
     *
     * @template ExpectedType
     *
     * @param ExpectedType $expected
     *
     * @phpstan-assert =ExpectedType $actual
     *
     * @see AbstractAsserts::assertSame()
     */
    public function assertSame(mixed $expected, mixed $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertSame', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Assert that the size of two arrays (or `Countable` or `Traversable` objects) is the same.
     *
     * @param \Countable|iterable<mixed> $expected
     * @param \Countable|iterable<mixed> $actual
     *
     * @see AbstractAsserts::assertSameSize()
     */
    public function assertSameSize(array | \Countable | \Traversable $expected, array | \Countable | \Traversable $actual, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertSameSize', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @see AbstractAsserts::assertStringContainsString()
     */
    public function assertStringContainsString(string $needle, string $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertStringContainsString', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @see AbstractAsserts::assertStringContainsStringIgnoringCase()
     */
    public function assertStringContainsStringIgnoringCase(string $needle, string $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertStringContainsStringIgnoringCase', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a string ends not with a given suffix.
     *
     * @param non-empty-string $suffix
     *
     * @see AbstractAsserts::assertStringEndsNotWith()
     */
    public function assertStringEndsNotWith(string $suffix, string $string, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertStringEndsNotWith', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a string ends with a given suffix.
     *
     * @param non-empty-string $suffix
     *
     * @see AbstractAsserts::assertStringEndsWith()
     */
    public function assertStringEndsWith(string $suffix, string $string, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertStringEndsWith', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that the contents of a string is equal to the contents of a file.
     *
     * @see AbstractAsserts::assertStringEqualsFile()
     */
    public function assertStringEqualsFile(string $expectedFile, string $actualString, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertStringEqualsFile', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that the contents of a string is equal to the contents of a file (canonicalizing).
     *
     * @see AbstractAsserts::assertStringEqualsFileCanonicalizing()
     */
    public function assertStringEqualsFileCanonicalizing(string $expectedFile, string $actualString, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertStringEqualsFileCanonicalizing', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that the contents of a string is equal to the contents of a file (ignoring case).
     *
     * @see AbstractAsserts::assertStringEqualsFileIgnoringCase()
     */
    public function assertStringEqualsFileIgnoringCase(string $expectedFile, string $actualString, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertStringEqualsFileIgnoringCase', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a string matches a given format string.
     *
     * @see AbstractAsserts::assertStringMatchesFormat()
     */
    public function assertStringMatchesFormat(string $format, string $string, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertStringMatchesFormat', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a string matches a given format file.
     *
     * @see AbstractAsserts::assertStringMatchesFormatFile()
     */
    public function assertStringMatchesFormatFile(string $formatFile, string $string, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertStringMatchesFormatFile', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @see AbstractAsserts::assertStringNotContainsString()
     */
    public function assertStringNotContainsString(string $needle, string $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertStringNotContainsString', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * @see AbstractAsserts::assertStringNotContainsStringIgnoringCase()
     */
    public function assertStringNotContainsStringIgnoringCase(string $needle, string $haystack, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertStringNotContainsStringIgnoringCase', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that the contents of a string is not equal to the contents of a file.
     *
     * @see AbstractAsserts::assertStringNotEqualsFile()
     */
    public function assertStringNotEqualsFile(string $expectedFile, string $actualString, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertStringNotEqualsFile', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that the contents of a string is not equal to the contents of a file (canonicalizing).
     *
     * @see AbstractAsserts::assertStringNotEqualsFileCanonicalizing()
     */
    public function assertStringNotEqualsFileCanonicalizing(string $expectedFile, string $actualString, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertStringNotEqualsFileCanonicalizing', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that the contents of a string is not equal to the contents of a file (ignoring case).
     *
     * @see AbstractAsserts::assertStringNotEqualsFileIgnoringCase()
     */
    public function assertStringNotEqualsFileIgnoringCase(string $expectedFile, string $actualString, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertStringNotEqualsFileIgnoringCase', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a string does not match a given format string.
     *
     * @see AbstractAsserts::assertStringNotMatchesFormat()
     */
    public function assertStringNotMatchesFormat(string $format, string $string, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertStringNotMatchesFormat', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a string does not match a given format string.
     *
     * @see AbstractAsserts::assertStringNotMatchesFormatFile()
     */
    public function assertStringNotMatchesFormatFile(string $formatFile, string $string, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertStringNotMatchesFormatFile', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a string starts not with a given prefix.
     *
     * @param non-empty-string $prefix
     *
     * @see AbstractAsserts::assertStringStartsNotWith()
     */
    public function assertStringStartsNotWith(string $prefix, string $string, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertStringStartsNotWith', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a string starts with a given prefix.
     *
     * @param non-empty-string $prefix
     *
     * @see AbstractAsserts::assertStringStartsWith()
     */
    public function assertStringStartsWith(string $prefix, string $string, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertStringStartsWith', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Evaluates a PHPUnit\Framework\Constraint matcher object.
     *
     * @param mixed $value
     *
     * @see AbstractAsserts::assertThat()
     */
    public function assertThat($value, Constraint $constraint, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertThat', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that a condition is true.
     *
     * @param mixed $condition
     *
     * @phpstan-assert true $condition
     *
     * @see AbstractAsserts::assertTrue()
     */
    public function assertTrue($condition, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertTrue', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that two XML files are equal.
     *
     * @see AbstractAsserts::assertXmlFileEqualsXmlFile()
     */
    public function assertXmlFileEqualsXmlFile(string $expectedFile, string $actualFile, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertXmlFileEqualsXmlFile', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that two XML files are not equal.
     *
     * @see AbstractAsserts::assertXmlFileNotEqualsXmlFile()
     */
    public function assertXmlFileNotEqualsXmlFile(string $expectedFile, string $actualFile, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertXmlFileNotEqualsXmlFile', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that two XML documents are equal.
     *
     * @see AbstractAsserts::assertXmlStringEqualsXmlFile()
     */
    public function assertXmlStringEqualsXmlFile(string $expectedFile, \DOMDocument | string $actualXml, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertXmlStringEqualsXmlFile', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that two XML documents are equal.
     *
     * @see AbstractAsserts::assertXmlStringEqualsXmlString()
     */
    public function assertXmlStringEqualsXmlString(\DOMDocument | string $expectedXml, \DOMDocument | string $actualXml, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertXmlStringEqualsXmlString', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that two XML documents are not equal.
     *
     * @param \DOMDocument|string $actualXml
     *
     * @see AbstractAsserts::assertXmlStringNotEqualsXmlFile()
     */
    public function assertXmlStringNotEqualsXmlFile(string $expectedFile, $actualXml, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertXmlStringNotEqualsXmlFile', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Asserts that two XML documents are not equal.
     *
     * @param \DOMDocument|string $expectedXml
     * @param \DOMDocument|string $actualXml
     *
     * @see AbstractAsserts::assertXmlStringNotEqualsXmlString()
     */
    public function assertXmlStringNotEqualsXmlString($expectedXml, $actualXml, string $message = ''): void
    {
        $this->getScenario()->runStep(new Action('assertXmlStringNotEqualsXmlString', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Fails a test with the given message.
     *
     * @see AbstractAsserts::fail()
     */
    public function fail(string $message = ''): never
    {
        $this->getScenario()->runStep(new Action('fail', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Mark the test as incomplete.
     *
     * @see AbstractAsserts::markTestIncomplete()
     */
    public function markTestIncomplete(string $message = ''): never
    {
        $this->getScenario()->runStep(new Action('markTestIncomplete', \func_get_args()));
    }

    /**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     * Mark the test as skipped.
     *
     * @see AbstractAsserts::markTestSkipped()
     */
    public function markTestSkipped(string $message = ''): never
    {
        $this->getScenario()->runStep(new Action('markTestSkipped', \func_get_args()));
    }

    /**
     * @return Scenario
     */
    abstract protected function getScenario();
}
